-- ============================================================================
-- Bethlehem Pet Grooming — Supabase (PostgreSQL) schema
-- ----------------------------------------------------------------------------
-- Faithful translation of the Laravel/MariaDB migrations (final state after all
-- 60+ migrations applied) into PostgreSQL for Supabase.
--
-- Translation rules applied:
--   int(10) UNSIGNED AUTO_INCREMENT  -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--   tinyint(1)                       -> BOOLEAN
--   datetime / timestamp             -> TIMESTAMPTZ
--   decimal(p,s)                     -> NUMERIC(p,s)
--   enum(...)                        -> TEXT + CHECK  (some were later widened to
--                                       varchar(50) in MySQL; those stay plain TEXT)
--   json                             -> JSONB
--   CURRENT_TIMESTAMP                -> now()
--   ON UPDATE CURRENT_TIMESTAMP      -> set_updated_at() trigger (see below)
--
-- NOTE: This app owns its own `users` table (role = customer/staff/admin). It is
-- intentionally NOT wired to Supabase `auth.users` — the AuthContext mirrors the
-- original session/challenge-based auth. If you later adopt Supabase Auth, map
-- auth.uid() -> users.user_id via a join table.
--
-- Pure Laravel framework plumbing (cache, cache_locks, jobs, job_batches,
-- failed_jobs, sessions, personal_access_tokens) is intentionally OMITTED — it is
-- runtime infrastructure with no domain meaning in a Node/Supabase stack.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Shared updated_at trigger (replaces MySQL "ON UPDATE CURRENT_TIMESTAMP")
-- ---------------------------------------------------------------------------
create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ============================================================================
-- CORE CATALOGS
-- ============================================================================

create table time_windows (
  window_id    bigint generated by default as identity primary key,
  window_label varchar(50) not null,
  start_time   time not null,
  end_time     time not null,
  max_slots    smallint not null default 4,
  is_active    boolean not null default true
);

create table services (
  service_id        bigint generated by default as identity primary key,
  service_name      varchar(150) not null,
  slug              varchar(100) unique,
  description       text,
  base_price        numeric(8,2) not null default 0,
  price_small       numeric(8,2),
  price_medium      numeric(8,2),
  price_large       numeric(8,2),
  price_extra_large numeric(8,2),
  price_min         numeric(8,2),
  price_max         numeric(8,2),
  is_starting_price boolean not null default false,
  is_active         boolean not null default true,
  duration_minutes  smallint,
  created_at        timestamptz not null default now()
);

create table addons (
  addon_id    bigint generated by default as identity primary key,
  addon_name  varchar(150) not null,
  description text,
  price       numeric(8,2) not null default 0,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- ============================================================================
-- IDENTITY
-- ============================================================================

create table users (
  user_id                        bigint generated by default as identity primary key,
  first_name                     varchar(100) not null,
  last_name                      varchar(100) not null,
  username                       varchar(50) unique,
  phone                          varchar(20) unique,           -- nullable since staff migration
  email                          varchar(150) not null unique,
  email_verified_at              timestamptz,
  email_verification_token       varchar(64) unique,
  email_verification_expires_at  timestamptz,
  password_hash                  varchar(255) not null,
  role                           text not null default 'customer'
                                   check (role in ('customer','staff','admin')),
  staff_type                     varchar(20),                  -- e.g. 'grooming', 'clinic'
  customer_tier                  varchar(20) not null default 'new'
                                   check (customer_tier in ('new','regular','frequent','inactive')),
  profile_photo                  varchar(255),
  is_active                      boolean not null default true,
  is_archived                    boolean not null default false,
  archived_at                    timestamptz,
  account_deleted_at             timestamptz,
  created_at                     timestamptz not null default now(),
  updated_at                     timestamptz not null default now()
);
create trigger users_set_updated_at before update on users
  for each row execute function set_updated_at();

create table unregistered_customers (
  id                  bigint generated by default as identity primary key,
  first_name          varchar(100) not null,
  last_name           varchar(100) not null,
  middle_name         varchar(5),
  phone               varchar(20) not null,
  email               varchar(150),
  created_by_user_id  bigint references users(user_id) on delete set null,
  is_archived         boolean not null default false,
  archived_at         timestamptz,
  account_deleted_at  timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create index uc_phone_idx on unregistered_customers(phone);
create index uc_email_idx on unregistered_customers(email);
create trigger uc_set_updated_at before update on unregistered_customers
  for each row execute function set_updated_at();

-- ============================================================================
-- PETS
-- ============================================================================

create table pets (
  pet_id                    bigint generated by default as identity primary key,
  user_id                   bigint references users(user_id) on delete cascade,               -- nullable for walk-in guests
  unregistered_customer_id  bigint references unregistered_customers(id) on delete set null,
  pet_name                  varchar(100) not null,
  species                   varchar(50) not null default 'Dog',
  breed                     varchar(100),
  gender                    text check (gender in ('male','female')),
  birthdate                 date,
  is_neutered               boolean not null default false,
  neutered_date             date,
  is_deceased               boolean not null default false,
  deceased_date             date,
  weight                    numeric(5,2),
  color                     varchar(50),
  size                      text check (size in ('small','medium','large','extra_large')),
  fur_type                  varchar(100),
  clinic_verified_fields    jsonb,
  medical_conditions        text,
  is_archived               boolean not null default false,
  created_at                timestamptz not null default now()
);
create index pets_user_idx on pets(user_id);

-- ============================================================================
-- WALK-INS
-- ============================================================================

create table walkins (
  id                        bigint generated by default as identity primary key,
  fname                     varchar(255) not null,
  lname                     varchar(255) not null,
  mname                     varchar(255),
  email                     varchar(255),
  phone                     varchar(255) not null,
  sedation_consent          boolean not null default false,
  terms_agreed              boolean not null default false,
  user_id                   bigint references users(user_id) on delete set null,
  unregistered_customer_id  bigint references unregistered_customers(id) on delete set null,
  appointment_type          text not null default 'grooming'
                              check (appointment_type in ('grooming','clinic')),
  chief_complaint           text,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);
create trigger walkins_set_updated_at before update on walkins
  for each row execute function set_updated_at();

-- ============================================================================
-- BOOKINGS (grooming)
-- ============================================================================

create table bookings (
  booking_id                     bigint generated by default as identity primary key,
  booking_reference              varchar(20) not null unique,
  user_id                        bigint references users(user_id) on delete cascade,   -- nullable for walk-ins
  walkin_id                      bigint references walkins(id) on delete set null,
  window_id                      bigint references time_windows(window_id) on delete set null,
  booking_date                   date not null,
  number_of_pets                 smallint not null default 1,
  booking_type                   text not null default 'online'
                                   check (booking_type in ('online','walk_in')),
  status                         text not null default 'waiting_to_arrive'
                                   check (status in (
                                     'waiting_to_arrive','checked_in','in_progress','for_pickup',
                                     'for_payment','released','archived','waiting','groomed',
                                     'waiting_for_payment','completed','cancelled','no_show')),
  archived_at                    timestamptz,
  paid                           boolean not null default false,
  dropped_off_at                 timestamptz,
  grooming_started_at            timestamptz,
  grooming_finished_at           timestamptz,
  queue_number                   integer,
  special_notes                  text,
  sedation_consent               boolean not null default false,
  sedation_consent_source        varchar(30),
  sedation_consent_recorded_by   bigint references users(user_id) on delete set null,
  sedation_consent_recorded_at   timestamptz,
  cancellation_reason            text,
  total_amount                   numeric(8,2) not null default 0,
  reschedule_count               smallint not null default 0,
  cancel_count                   smallint not null default 0,
  created_at                     timestamptz not null default now(),
  updated_at                     timestamptz not null default now()
);
create index bookings_user_idx on bookings(user_id);
create index bookings_status_idx on bookings(status);
create trigger bookings_set_updated_at before update on bookings
  for each row execute function set_updated_at();

create table booking_pets (
  booking_pet_id        bigint generated by default as identity primary key,
  booking_id            bigint not null references bookings(booking_id) on delete cascade,
  pet_id                bigint references pets(pet_id) on delete set null,
  pet_queue_date        date,
  pet_queue_number      integer,
  special_instructions  text,
  groomer_id            bigint references users(user_id) on delete set null,
  grooming_start_time   timestamptz,
  grooming_end_time     timestamptz,
  grooming_state        varchar(20) not null default 'not_started',
  registered_size       varchar(20),
  confirmed_size        varchar(20),
  -- composite unique required by the medical-concern composite FKs
  constraint bp_concern_identity_uq unique (booking_pet_id, booking_id, pet_id),
  constraint booking_pets_daily_queue_unique unique (pet_queue_date, pet_queue_number)
);
create index bp_grooming_state_idx on booking_pets(grooming_state);

create table booking_services (
  booking_service_id  bigint generated by default as identity primary key,
  booking_id          bigint not null references bookings(booking_id) on delete cascade,
  booking_pet_id      bigint not null references booking_pets(booking_pet_id) on delete cascade,
  service_id          bigint references services(service_id) on delete set null,
  addon_id            bigint references addons(addon_id) on delete set null,
  price_at_booking    numeric(8,2) not null default 0
);

-- ============================================================================
-- PAYMENTS
-- ============================================================================

create table payments (
  id              bigint generated by default as identity primary key,
  booking_id      bigint not null references bookings(booking_id) on delete cascade,
  total_amount    numeric(10,2) not null,
  amount_tendered numeric(10,2),
  change_amount   numeric(10,2),
  payment_method  text not null default 'cash'
                    check (payment_method in ('cash','gcash','maya','card','others')),
  payment_status  text not null default 'pending'
                    check (payment_status in ('pending','paid')),
  notes           text,
  paid_at         timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create trigger payments_set_updated_at before update on payments
  for each row execute function set_updated_at();

-- ============================================================================
-- CLINIC
-- ============================================================================

create table clinic_closures (
  id         bigint generated by default as identity primary key,
  type       text not null check (type in ('stop_today','blocked_date')),
  start_date date not null,
  end_date   date not null,
  reason     varchar(255),
  is_active  boolean not null default true,
  created_by bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create trigger clinic_closures_set_updated_at before update on clinic_closures
  for each row execute function set_updated_at();

create table clinic_settings (
  id                          bigint generated by default as identity primary key,
  groomers_on_duty            smallint not null default 2,
  clinic_open_time            time not null default '08:00:00',
  clinic_close_time           time not null default '17:00:00',
  clinic_prereg_cutoff_time   time not null default '14:00:00',
  grooming_open_time          time not null default '08:00:00',
  grooming_close_time         time not null default '17:00:00',
  grooming_prereg_cutoff_time time not null default '14:00:00',
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now()
);
create trigger clinic_settings_set_updated_at before update on clinic_settings
  for each row execute function set_updated_at();
insert into clinic_settings (id, groomers_on_duty) values (1, 2);

create table clinic_appointments (
  id                        bigint generated by default as identity primary key,
  appointment_reference     varchar(30) not null unique,
  appointment_type          text not null default 'walk_in'
                              check (appointment_type in ('walk_in','pre_registered')),
  status                    text not null default 'checked_in'
                              check (status in ('waiting_to_arrive','checked_in','in_consultation',
                                                'for_payment','completed','cancelled','no_show')),
  queue_number              smallint,
  appointment_date          date not null,
  window_id                 bigint references time_windows(window_id) on delete set null,
  user_id                   bigint references users(user_id) on delete set null,
  walkin_id                 bigint references walkins(id) on delete set null,
  pet_id                    bigint references pets(pet_id) on delete set null,
  chief_complaint           text,
  total_amount              numeric(10,2),
  paid                      boolean not null default false,
  notes                     text,
  checked_in_at             timestamptz,
  consultation_started_at   timestamptz,
  consultation_finished_at  timestamptz,
  archived_at               timestamptz,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);
create trigger clinic_appointments_set_updated_at before update on clinic_appointments
  for each row execute function set_updated_at();

create table clinic_records (
  id                   bigint generated by default as identity primary key,
  clinic_appointment_id bigint not null unique references clinic_appointments(id) on delete cascade,
  chief_complaint      text,
  diagnosis            text,
  findings             text,
  treatment_given      text,
  follow_up_date       date,
  follow_up_notes      text,
  vet_notes            text,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create trigger clinic_records_set_updated_at before update on clinic_records
  for each row execute function set_updated_at();

create table clinic_vitals (
  id                    bigint generated by default as identity primary key,
  clinic_appointment_id bigint not null unique references clinic_appointments(id) on delete cascade,
  weight_kg             numeric(5,2),
  temperature_c         numeric(4,1),
  heart_rate_bpm        smallint,
  respiratory_rate_bpm  smallint,
  body_condition_score  smallint,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
create trigger clinic_vitals_set_updated_at before update on clinic_vitals
  for each row execute function set_updated_at();

create table clinic_attachments (
  id               bigint generated by default as identity primary key,
  clinic_record_id bigint not null references clinic_records(id) on delete cascade,
  file_name        varchar(255) not null,
  file_path        varchar(500) not null,
  file_type        varchar(100),
  file_size_bytes  integer,
  label            varchar(255),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create trigger clinic_attachments_set_updated_at before update on clinic_attachments
  for each row execute function set_updated_at();

create table clinic_medications (
  id               bigint generated by default as identity primary key,
  clinic_record_id bigint not null references clinic_records(id) on delete cascade,
  drug_name        varchar(200) not null,
  dosage           varchar(100),
  frequency        varchar(100),
  duration         varchar(100),
  instructions     text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create trigger clinic_medications_set_updated_at before update on clinic_medications
  for each row execute function set_updated_at();

-- ============================================================================
-- INVENTORY & POS
-- ============================================================================

create table suppliers (
  supplier_id    bigint generated by default as identity primary key,
  supplier_name  varchar(150) not null,
  contact_person varchar(100),
  phone          varchar(30),
  email          varchar(100),
  address        text,
  notes          text,
  is_active      boolean not null default true,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);
create trigger suppliers_set_updated_at before update on suppliers
  for each row execute function set_updated_at();

create table inventory_items (
  item_id          bigint generated by default as identity primary key,
  item_name        varchar(150) not null,
  barcode          varchar(100) unique,
  category         text not null check (category in
                     ('medicine','vaccine','food','grooming_supply','pet_shop','miscellaneous')),
  unit             varchar(50) not null,
  description      varchar(255),
  expiry_date      date,
  unit_cost        numeric(8,2) not null default 0,
  selling_price    numeric(8,2),
  quantity_on_hand numeric(10,2) not null default 0,
  reorder_level    numeric(10,2) not null default 0,
  is_active        boolean not null default true,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create trigger inventory_items_set_updated_at before update on inventory_items
  for each row execute function set_updated_at();

create table inventory_transactions (
  transaction_id        bigint generated by default as identity primary key,
  item_id               bigint not null references inventory_items(item_id) on delete cascade,
  type                  text not null check (type in ('stock_in','stock_out')),
  quantity              numeric(10,2) not null,
  unit_cost_at_time     numeric(8,2),
  selling_price_at_time numeric(8,2),
  reason                text not null check (reason in
                          ('purchase','return','used','sold','expired','damaged','adjustment')),
  supplier_id           bigint references suppliers(supplier_id) on delete set null,
  batch_number          varchar(100),
  expiry_date           date,
  reference_type        text not null default 'manual'
                          check (reference_type in ('manual','appointment','pos')),
  reference_id          bigint,
  notes                 text,
  performed_by          bigint references users(user_id) on delete set null,
  created_at            timestamptz not null default now()
);
create index inv_tx_item_idx on inventory_transactions(item_id);

create table pos_transactions (
  pos_id          bigint generated by default as identity primary key,
  cashier_id      bigint not null references users(user_id),
  total_amount    numeric(8,2) not null,
  amount_tendered numeric(8,2) not null,
  change_amount   numeric(8,2) not null,
  notes           text,
  created_at      timestamptz not null default now()
);

create table pos_transaction_items (
  id            bigint generated by default as identity primary key,
  pos_id        bigint not null references pos_transactions(pos_id) on delete cascade,
  item_id       bigint not null references inventory_items(item_id),
  quantity      numeric(10,2) not null,
  price_at_sale numeric(8,2) not null,
  subtotal      numeric(8,2) not null
);

-- ============================================================================
-- VACCINATIONS
-- ============================================================================

create table vaccination_records (
  id                       bigint generated by default as identity primary key,
  pet_id                   bigint not null references pets(pet_id) on delete restrict,
  clinic_appointment_id    bigint references clinic_appointments(id) on delete set null,
  inventory_item_id        bigint references inventory_items(item_id) on delete set null,
  vaccine_name             varchar(150) not null,
  product_name             varchar(150),
  manufacturer             varchar(150),
  batch_number             varchar(100),
  administered_date        date not null,
  next_due_date            date,
  product_expiry_date      date,
  dose_amount              numeric(8,3),
  dose_unit                varchar(30),
  route                    varchar(50),
  administration_site      varchar(100),
  administered_by_user_id  bigint references users(user_id) on delete set null,
  administered_by_name     varchar(200),
  recorded_by_user_id      bigint references users(user_id) on delete set null,
  notes                    text,
  published_at             timestamptz,
  published_by_user_id     bigint references users(user_id) on delete set null,
  voided_at                timestamptz,
  voided_by_user_id        bigint references users(user_id) on delete set null,
  void_reason              varchar(500),
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);
create index vaccination_pet_date_idx on vaccination_records(pet_id, administered_date);
create index vaccination_client_visibility_idx on vaccination_records(pet_id, published_at);
create index vaccination_next_due_idx on vaccination_records(next_due_date);
create index vaccination_duplicate_lookup_idx on vaccination_records(pet_id, vaccine_name, administered_date);
create trigger vaccination_records_set_updated_at before update on vaccination_records
  for each row execute function set_updated_at();

-- ============================================================================
-- GROOMING MEDICAL CONCERNS  ->  CLINIC REFERRALS  ->  STOPPED-PAYMENT REVIEWS
-- ============================================================================

create table grooming_medical_concerns (
  id                            bigint generated by default as identity primary key,
  public_id                     uuid not null,
  report_token                  uuid,
  booking_id                    bigint not null,
  booking_pet_id                bigint not null,
  pet_id                        bigint not null,
  reported_by_user_id           bigint references users(user_id) on delete set null,
  reported_by_name              varchar(200) not null,
  reported_at                   timestamptz not null default now(),
  category                      varchar(50) not null,
  severity                      varchar(20) not null,
  internal_description          text not null,
  customer_message              text not null,
  recommended_grooming_action   varchar(40) not null,
  applied_grooming_action       varchar(40),
  action_applied_at             timestamptz,
  action_applied_by_user_id     bigint references users(user_id) on delete set null,
  status                        varchar(30) not null default 'open',
  acknowledgment_required       boolean not null default false,
  consent_required              boolean not null default false,
  customer_response_status      varchar(30) not null default 'not_required',
  customer_notified_at          timestamptz,
  clinic_appointment_id         bigint references clinic_appointments(id) on delete restrict,
  customer_resolution_summary   text,
  internal_resolution_notes     text,
  resolved_at                   timestamptz,
  resolved_by_user_id           bigint references users(user_id) on delete set null,
  resolved_by_name              varchar(200),
  created_at                    timestamptz not null default now(),
  updated_at                    timestamptz not null default now(),
  constraint gmc_public_id_uq unique (public_id),
  constraint gmc_report_token_uq unique (report_token),
  -- required by the stopped-payment-review composite FK
  constraint gmc_review_context_uq unique (id, booking_id, booking_pet_id, pet_id),
  constraint gmc_booking_pet_fk foreign key (booking_pet_id, booking_id, pet_id)
    references booking_pets (booking_pet_id, booking_id, pet_id) on delete restrict
);
create index gmc_booking_pet_status_idx on grooming_medical_concerns(booking_pet_id, status);
create index gmc_pet_status_idx on grooming_medical_concerns(pet_id, status);
create trigger gmc_set_updated_at before update on grooming_medical_concerns
  for each row execute function set_updated_at();

create table grooming_medical_concern_responses (
  id                    bigint generated by default as identity primary key,
  concern_id            bigint not null references grooming_medical_concerns(id) on delete restrict,
  responded_by_user_id  bigint references users(user_id) on delete set null,
  responded_by_name     varchar(200) not null,
  response_channel      varchar(30) not null default 'portal',
  captured_by_user_id   bigint references users(user_id) on delete set null,
  captured_by_name      varchar(200),
  response_kind         varchar(30) not null,
  decision              varchar(30) not null,
  statement_text        text not null,
  statement_version     varchar(50) not null,
  signature_name        varchar(200),
  responded_at          timestamptz not null default now(),
  created_at            timestamptz not null default now(),
  constraint gmcr_concern_kind_uq unique (concern_id, response_kind),
  constraint gmcr_ref_context_uq unique (id, concern_id)
);
create index gmcr_concern_responded_idx on grooming_medical_concern_responses(concern_id, responded_at);

create table grooming_clinic_referrals (
  id                                bigint generated by default as identity primary key,
  public_id                         uuid not null,
  request_token                     uuid,
  grooming_medical_concern_id       bigint not null,
  booking_id                        bigint not null,
  booking_pet_id                    bigint not null,
  pet_id                            bigint not null,
  clinic_appointment_id             bigint,
  status                            varchar(30) not null,
  urgency                           varchar(20) not null,
  referral_reason                   text not null,
  customer_explanation              text not null,
  consent_required                  boolean not null default true,
  consent_response_id               bigint,
  owner_user_id_at_referral         bigint,
  owner_name_at_referral            varchar(200) not null,
  referred_by_user_id               bigint,
  referred_by_name                  varchar(200) not null,
  referred_at                       timestamptz not null default now(),
  customer_notified_at              timestamptz,
  emergency_without_consent_reason  text,
  accepted_by_user_id               bigint,
  accepted_by_name                  varchar(200),
  accepted_at                       timestamptz,
  clinic_review_started_by_user_id  bigint,
  clinic_review_started_by_name     varchar(200),
  clinic_review_started_at          timestamptz,
  grooming_clearance_status         varchar(30) not null default 'pending',
  cancelled_by_user_id              bigint,
  cancelled_by_name                 varchar(200),
  cancelled_at                      timestamptz,
  cancellation_reason               text,
  customer_cancellation_summary     text,
  resolved_by_user_id               bigint,
  resolved_by_name                  varchar(200),
  resolved_at                       timestamptz,
  internal_resolution_notes         text,
  customer_resolution_summary       text,
  created_at                        timestamptz not null default now(),
  constraint gcr_public_uq unique (public_id),
  constraint gcr_token_uq unique (request_token),
  constraint gcr_concern_uq unique (grooming_medical_concern_id),
  constraint gcr_appt_uq unique (clinic_appointment_id),
  constraint gcr_consent_uq unique (consent_response_id),
  constraint gcr_concern_fk foreign key (grooming_medical_concern_id)
    references grooming_medical_concerns(id) on delete restrict,
  constraint gcr_clinic_appt_fk foreign key (clinic_appointment_id)
    references clinic_appointments(id) on delete set null,
  constraint gcr_consent_fk foreign key (consent_response_id)
    references grooming_medical_concern_responses(id) on delete set null
);
create index gcr_booking_status_idx on grooming_clinic_referrals(booking_id, status);
create index gcr_pet_referred_idx on grooming_clinic_referrals(pet_id, referred_at);
create index gcr_status_urgency_idx on grooming_clinic_referrals(status, urgency, referred_at);

create table grooming_stopped_payment_reviews (
  id                            bigint generated by default as identity primary key,
  booking_id                    bigint not null,
  booking_pet_id                bigint not null,
  pet_id                        bigint not null,
  grooming_medical_concern_id   bigint not null,
  decision                      varchar(20) not null,
  original_pet_subtotal         numeric(8,2) not null,
  final_pet_charge              numeric(8,2) not null,
  internal_reason               text not null,
  customer_explanation          text not null,
  reviewed_by_user_id           bigint references users(user_id) on delete set null,
  reviewed_by_name              varchar(200) not null,
  reviewed_at                   timestamptz not null default now(),
  created_at                    timestamptz not null default now(),
  constraint gspr_booking_pet_uq unique (booking_pet_id),
  constraint gspr_concern_uq unique (grooming_medical_concern_id),
  constraint gspr_booking_fk foreign key (booking_id)
    references bookings(booking_id) on delete restrict,
  constraint gspr_pet_fk foreign key (pet_id)
    references pets(pet_id) on delete restrict,
  constraint gspr_booking_pet_ctx_fk foreign key (booking_pet_id, booking_id, pet_id)
    references booking_pets(booking_pet_id, booking_id, pet_id) on delete restrict,
  constraint gspr_concern_ctx_fk foreign key (grooming_medical_concern_id, booking_id, booking_pet_id, pet_id)
    references grooming_medical_concerns(id, booking_id, booking_pet_id, pet_id) on delete restrict
);
create index gspr_booking_reviewed_idx on grooming_stopped_payment_reviews(booking_id, reviewed_at);
create index gspr_decision_idx on grooming_stopped_payment_reviews(decision);

-- ============================================================================
-- NOTIFICATIONS
-- ============================================================================

-- Admin/staff notifications (type + booking_id widened to nullable/string over time)
create table notifications (
  notification_id       bigint generated by default as identity primary key,
  type                  varchar(50) not null,
  booking_id            bigint references bookings(booking_id) on delete cascade,
  clinic_appointment_id bigint references clinic_appointments(id) on delete cascade,
  message               text not null,
  is_read               boolean not null default false,
  created_at            timestamptz not null default now()
);
create index admin_notif_type_read_created_idx on notifications(type, is_read, created_at);
create index admin_notif_read_created_idx on notifications(is_read, created_at);

-- Customer-facing notifications
create table customer_notifications (
  id                            bigint generated by default as identity primary key,
  user_id                       bigint not null,
  booking_id                    bigint,
  pet_id                        bigint references pets(pet_id) on delete set null,
  type                          varchar(50) not null,
  message                       text not null,
  is_read                       boolean not null default false,
  grooming_medical_concern_id   bigint references grooming_medical_concerns(id) on delete restrict,
  grooming_clinic_referral_id   bigint references grooming_clinic_referrals(id) on delete restrict,
  created_at                    timestamptz not null default now(),
  constraint cn_referral_type_uq unique (grooming_clinic_referral_id, type)
);
create index cn_user_idx on customer_notifications(user_id);

-- ============================================================================
-- AUTH FLOWS: registration, email/login challenges, credential changes, resets
-- ============================================================================

create table pending_customer_registrations (
  id                             bigint generated by default as identity primary key,
  first_name                     varchar(100) not null,
  last_name                      varchar(100) not null,
  username                       varchar(50) unique,
  phone                          varchar(20) not null unique,
  email                          varchar(150) not null unique,
  password_hash                  varchar(255) not null,
  email_verification_token       varchar(64) unique,
  email_verification_expires_at  timestamptz,
  created_at                     timestamptz not null default now(),
  updated_at                     timestamptz not null default now()
);
create trigger pcr_set_updated_at before update on pending_customer_registrations
  for each row execute function set_updated_at();

create table login_email_challenges (
  id              bigint generated by default as identity primary key,
  user_id         bigint not null unique references users(user_id) on delete cascade,
  token_hash      varchar(64) not null unique,
  poll_token_hash varchar(64) unique,
  remember_me     boolean not null default true,
  expires_at      timestamptz not null,
  approved_at     timestamptz,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index lec_expires_idx on login_email_challenges(expires_at);
create trigger lec_set_updated_at before update on login_email_challenges
  for each row execute function set_updated_at();

create table privileged_credential_changes (
  id                    bigint generated by default as identity primary key,
  requested_by_user_id  bigint not null references users(user_id) on delete cascade,
  target_user_id        bigint not null references users(user_id) on delete cascade,
  target_role           varchar(20) not null,
  new_username          varchar(50),
  new_password_hash     varchar(255),
  changes_password      boolean not null default false,
  code_hash             varchar(255),
  failed_attempts       smallint not null default 0,
  last_sent_at          timestamptz,
  expires_at            timestamptz,
  confirmed_at          timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
create index credential_changes_target_pending_idx on privileged_credential_changes(target_user_id, confirmed_at);
create trigger pcc_set_updated_at before update on privileged_credential_changes
  for each row execute function set_updated_at();

create table password_reset_requests (
  id           bigint generated by default as identity primary key,
  user_id      bigint not null unique references users(user_id) on delete cascade,
  token_hash   varchar(64) not null unique,
  expires_at   timestamptz not null,
  last_sent_at timestamptz not null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);
create index prr_expires_idx on password_reset_requests(expires_at);
create trigger prr_set_updated_at before update on password_reset_requests
  for each row execute function set_updated_at();

create table pending_staff_accounts (
  id                    bigint generated by default as identity primary key,
  requested_by_user_id  bigint not null references users(user_id) on delete cascade,
  staff_type            varchar(20) not null,
  username              varchar(50) unique,
  email                 varchar(150) not null unique,
  password_hash         varchar(255) not null,
  code_hash             varchar(255) not null,
  failed_attempts       smallint not null default 0,
  expires_at            timestamptz not null,
  last_sent_at          timestamptz not null,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
create trigger psa_set_updated_at before update on pending_staff_accounts
  for each row execute function set_updated_at();

-- ============================================================================
-- CHATBOT INSIGHTS
-- ============================================================================

create table chatbot_insights (
  id                   bigint generated by default as identity primary key,
  question_fingerprint char(64) not null unique,
  question_excerpt     varchar(500) not null,
  language             varchar(16) not null default 'unknown',
  failure_reason       varchar(50) not null,
  occurrence_count     integer not null default 1,
  status               varchar(20) not null default 'new',
  first_seen_at        timestamptz not null,
  last_seen_at         timestamptz not null,
  reviewed_by_user_id  bigint references users(user_id) on delete set null,
  resolved_at          timestamptz,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);
create index chatbot_insights_status_idx on chatbot_insights(status);
create index chatbot_insights_last_seen_idx on chatbot_insights(last_seen_at);
create trigger chatbot_insights_set_updated_at before update on chatbot_insights
  for each row execute function set_updated_at();

create table chatbot_feedback (
  id               bigint generated by default as identity primary key,
  response_id      uuid not null unique,
  helpful          boolean not null,
  question_excerpt varchar(500) not null,
  answer_excerpt   varchar(800) not null,
  answer_source    varchar(40) not null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz
);
