// Faithful page extractor.
//
// Reads the ORIGINAL static HTML pages and emits, for each one, a verbatim
// body-markup partial (design untouched) plus a manifest entry with the exact
// <body> class list. Only <script> tags are removed (behavior, not design) and
// asset URLs are repointed to /assets (already copied into public/). We do NOT
// rewrite, restyle, or re-author any markup.
import { readFileSync, writeFileSync, mkdirSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

const SRC = process.env.BPG_SRC || '/tmp/bpg/BethlehemPetGrooming-main/pages';
const OUT = new URL('../src/pages/_source/', import.meta.url).pathname;

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...walk(p));
    else if (name.endsWith('.html')) out.push(p);
  }
  return out;
}

function slug(relPath) {
  // pages/client/booking-services.html -> client__booking-services
  return relPath.replace(/\.html$/, '').replace(/[\/]/g, '__');
}

function extract(html) {
  const bodyOpen = html.match(/<body([^>]*)>/i);
  const bodyClass = (bodyOpen?.[1].match(/class="([^"]*)"/i)?.[1]) ?? '';
  const iconLib = bodyOpen?.[1].match(/data-icon-library="([^"]*)"/i)?.[1] ?? '';
  const title = html.match(/<title>([^<]*)<\/title>/i)?.[1]?.trim() ?? '';

  let inner = html.replace(/[\s\S]*<body[^>]*>/i, '').replace(/<\/body>[\s\S]*/i, '');
  // Remove script tags (behavior). Keep everything else verbatim.
  inner = inner.replace(/<script[\s\S]*?<\/script>/gi, '');
  inner = inner.replace(/<script[^>]*\/>/gi, '');
  // Repoint asset URLs to the copied public/assets.
  inner = inner.replace(/(?:\.\.\/)+assets\//g, '/assets/');
  // Neutralize hard links to other .html files so they don't blow away the SPA.
  inner = inner.replace(/href="[^"]*\.html[^"]*"/gi, 'href="#"');
  return { bodyClass, iconLib, title, inner: inner.trim() };
}

mkdirSync(OUT, { recursive: true });
const files = walk(SRC).sort();
const manifest = [];
for (const file of files) {
  const rel = relative(SRC.replace(/\/pages$/, ''), file); // pages/client/x.html
  const relFromPages = relative(SRC, file); // client/x.html
  const { bodyClass, iconLib, title, inner } = extract(readFileSync(file, 'utf8'));
  const key = slug(relFromPages);
  writeFileSync(join(OUT, key + '.html'), inner + '\n');
  manifest.push({ key, source: rel, bodyClass, iconLib, title });
}

// Emit a typed manifest that lazy-imports each partial as a raw string.
const lines = [
  '// AUTO-GENERATED by scripts/build-pages.mjs — do not edit by hand.',
  '// Each entry renders the verbatim body markup of the original page.',
  'export interface PageMeta {',
  '  key: string;',
  '  source: string;',
  '  bodyClass: string;',
  '  iconLib: string;',
  '  title: string;',
  '  load: () => Promise<string>;',
  '}',
  '',
  'export const PAGES: Record<string, PageMeta> = {',
];
for (const m of manifest) {
  lines.push(
    `  '${m.key}': { key: '${m.key}', source: ${JSON.stringify(m.source)}, ` +
      `bodyClass: ${JSON.stringify(m.bodyClass)}, iconLib: ${JSON.stringify(m.iconLib)}, ` +
      `title: ${JSON.stringify(m.title)}, ` +
      `load: () => import('./_source/${m.key}.html?raw').then((m) => m.default) },`,
  );
}
lines.push('};', '');
writeFileSync(new URL('../src/pages/generated.ts', import.meta.url).pathname, lines.join('\n'));
console.log(`Extracted ${manifest.length} pages -> src/pages/_source/ + generated.ts`);
